development:
  adapter: postgresql
  encoding: unicode
  database: cookbook_development
  pool: 5
  username: zarapeisker
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: cookbook_test
  pool: 5
  username: zarapeisker
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: cookbook_production
  pool: 5
  username: zarapeisker
  password:
  host: localhost
